import { FileTextIcon, ListChecksIcon, UsersIcon } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

// The special (non-chart) slide types a user can add to a report. Their CONTENT
// (heading + bullets, or the demographics grid) is generated by AI and edited in
// the Design step; here the user only chooses which one to create.
const SPECIAL_SLIDE_CHOICES: {
  type: string;
  label: string;
  description: string;
  Icon: typeof FileTextIcon;
}[] = [
  {
    type: "special_overview",
    label: "Overview",
    description: "Background about the research, generated from the available information.",
    Icon: FileTextIcon,
  },
  {
    type: "special_conclusion",
    label: "Conclusion",
    description: "The major conclusions drawn across the report's questions.",
    Icon: ListChecksIcon,
  },
  {
    type: "special_demographics",
    label: "Demographics",
    description: "Facts about the respondents plus a chart per demographic question.",
    Icon: UsersIcon,
  },
];

export function AddSpecialDialog({
  open,
  onOpenChange,
  existingTypes,
  onPick,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  existingTypes: Set<string>;
  onPick: (type: string) => void;
}) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Add a special slide</DialogTitle>
          <DialogDescription>
            Special slides are written by AI from the report's data.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          {SPECIAL_SLIDE_CHOICES.map(({ type, label, description, Icon }) => {
            const added = existingTypes.has(type);
            return (
              <button
                key={type}
                type="button"
                disabled={added}
                onClick={() => {
                  onPick(type);
                  onOpenChange(false);
                }}
                className="flex w-full items-start gap-3 rounded-lg border p-3 text-left transition-colors hover:bg-accent/50 disabled:pointer-events-none disabled:opacity-50"
              >
                <div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <Icon className="size-4" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-medium">
                    {label}
                    {added && (
                      <span className="ml-2 text-xs font-normal text-muted-foreground">
                        Added
                      </span>
                    )}
                  </p>
                  <p className="mt-0.5 text-xs text-muted-foreground">{description}</p>
                </div>
              </button>
            );
          })}
        </div>
      </DialogContent>
    </Dialog>
  );
}
