import { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import {
  AlertCircleIcon,
  BarChart3Icon,
  GripVerticalIcon,
  ImageIcon,
  InfoIcon,
  Loader2Icon,
  RotateCcwIcon,
  SparklesIcon,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { api } from "@/lib/api";
import type { ChartSpec, ConfigField, Question, Variable, GroupingOverride } from "@/lib/api";
import { useChartPreview, useChartTypes, useRegroupedQuestions, useVariables } from "@/lib/queries";
import { useDragReorder } from "@/lib/useDragReorder";
import { slideTitle } from "@/components/wizard/SlideGrid";
import QuestionDetailsDialog from "@/components/QuestionDetailsDialog";
import {
  CHART_TYPES,
  CHART_TYPE_ITEMS,
  NUMBER_FORMAT_ITEMS,
  SORT_DIRECTIONS,
  isDemographicsGrid,
  isThemes,
  isWordcloud,
  rendersAsBullets,
  rendersFullSlide,
  slideSubtitle,
  SLIDE_ASPECT,
  defaultRowSummaryLabel,
} from "@/lib/charts";

// The report's grouping override, shared with the leaf preview components so a
// chart on a manually-grouped question previews the way it renders.
const GroupingCtx = createContext<GroupingOverride>({ groups: [], singles: [] });

// Per-chart pending flags (keyed by question_ref) from the auto-AI orchestrator.
export type AiPendingMap = Record<
  string,
  { titlePending: boolean; labelsPending: boolean; bulletsPending?: boolean }
>;

type Region = { left: string; top: string; width: string; height: string };

// Where the category labels are baked into the rendered PNG, per chart type, so
// the "Shortening labels…" placeholder can sit over the right area. Percentages
// map onto the 4:3 image because the container is constrained to that aspect.
function labelRegion(chartType: string): Region {
  switch (chartType) {
    case "horizontal_bar":
    case "stacked_horizontal_bar":
      // Left gutter where the category labels run down the y-axis.
      return { left: "1.5%", top: "20%", width: "24%", height: "66%" };
    case "pie":
    case "doughnut":
      // Right-hand legend.
      return { left: "71%", top: "22%", width: "27.5%", height: "60%" };
    case "radar":
      // Perimeter labels — a small centered chip rather than a box.
      return { left: "37%", top: "44%", width: "26%", height: "12%" };
    default:
      // vertical_bar / stacked_vertical_bar / line / combo / funnel — x-axis.
      return { left: "6%", top: "82%", width: "88%", height: "14%" };
  }
}

// Dashed placeholder over a region still being generated by the AI.
function PendingRegion({
  style,
  label,
}: {
  style: React.CSSProperties;
  label: string;
}) {
  return (
    <div
      className="absolute z-10 flex items-center justify-center rounded-lg border-2 border-dashed border-white/40 bg-black/80 px-2 text-center"
      style={style}
    >
      <span className="flex items-center gap-1.5 text-xs font-medium text-white/90">
        <SparklesIcon className="size-3.5 shrink-0 animate-pulse text-white" />
        {label}
      </span>
    </div>
  );
}

// ── Live preview ──────────────────────────────────────────────────────────
function ChartPreview({
  materialId,
  chart,
  titlePending,
  labelsPending,
  questionText,
}: {
  materialId: string;
  chart: ChartSpec;
  titlePending: boolean;
  labelsPending: boolean;
  questionText: string;
}) {
  // Debounce live edits so typing/toggling doesn't fire a render per keystroke.
  // Unchanged charts resolve INSTANTLY from the shared cache (formed once).
  const editKey = useMemo(() => JSON.stringify(chart), [chart]);
  const chartRef = useRef(chart);
  chartRef.current = chart;
  const [debounced, setDebounced] = useState(chart);
  useEffect(() => {
    const h = setTimeout(() => setDebounced(chartRef.current), 350);
    return () => clearTimeout(h);
  }, [editKey]);

  // render_title:true — the PNG is the FULL slide (title baked in), so the Design
  // preview is IDENTICAL to the Overview grid and the exported deck (WYSIWYG).
  void questionText;
  const grouping = useContext(GroupingCtx);
  const { data: url, error: qError, isFetching: loading } = useChartPreview(
    materialId,
    debounced,
    { renderTitle: true, priority: true, grouping }
  );
  const error =
    qError instanceof Error ? qError.message : qError ? "Preview failed" : null;

  const region = labelRegion(chart.chart_type);

  return (
    // Full-width preview: no padding — the border frames the slide itself. The
    // box matches the slide's aspect ratio, so the height follows the available
    // width and there's no white space around the slide. (SLIDE_ASPECT)
    <div className={`relative w-full overflow-hidden rounded-lg border bg-muted/30 ${SLIDE_ASPECT}`}>
        {url ? (
          <img
            src={url}
            alt="Chart preview"
            className="absolute inset-0 size-full object-contain"
          />
        ) : (
          !error && (
            <div className="flex size-full flex-col items-center justify-center gap-3 text-muted-foreground">
              <ImageIcon className="size-8 opacity-40" />
              <span className="text-sm">Rendering preview…</span>
            </div>
          )
        )}

        {/* The title is baked into the PNG (renderTitle:true). While the AI title
            is (re)generating, cover its region with a pending placeholder. */}
        {url && titlePending && (
          <PendingRegion
            style={{ left: "4%", top: "2.5%", width: "92%", height: "13%" }}
            label="Generating title…"
          />
        )}

        {/* Label region — placed per chart type; clears when labels land. A
            word cloud has no category labels, so it never shows this overlay. */}
        {url && labelsPending && !isWordcloud(chart.chart_type) && (
          <PendingRegion
            style={{
              left: region.left,
              top: region.top,
              width: region.width,
              height: region.height,
            }}
            label="Shortening labels…"
          />
        )}

        {loading && url && (
          <div className="absolute inset-0 z-20 flex items-center justify-center">
            <div className="flex items-center gap-2.5 rounded-full bg-background/95 px-5 py-2.5 text-sm font-semibold text-foreground shadow-lg ring-1 ring-border backdrop-blur-sm">
              <div className="size-4 animate-spin rounded-full border-2 border-primary border-t-transparent" />
              Updating…
            </div>
          </div>
        )}

        {error && (
          <div className="absolute inset-x-4 bottom-4 z-20 flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive shadow-sm">
            <AlertCircleIcon className="mt-0.5 size-4 shrink-0" />
            <span className="leading-snug">{error}</span>
          </div>
        )}
    </div>
  );
}

// ── A labelled control row ──────────────────────────────────────────────────
function Field({
  label,
  required,
  children,
}: {
  label: string;
  required?: boolean;
  // Accepted for call-site compatibility but no longer rendered — the orange
  // per-field "tips" were removed from the config section.
  hint?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-1.5">
      <Label className="text-xs font-medium text-muted-foreground">
        {label}
        {required && <span className="ml-1 text-destructive">*</span>}
      </Label>
      {children}
    </div>
  );
}

// ── Schema-driven config form ───────────────────────────────────────────────
// The per-chart config form is rendered entirely from the active chart type's
// plugin-declared schema (GET /chart-types). Adding a chart type — or a new
// option of an EXISTING widget type — needs no change here; only a brand-new
// widget type does.

interface WidgetProps {
  field: ConfigField;
  chart: ChartSpec;
  materialId: string;
  question: Question | undefined;
  variables: Variable[] | undefined;
  onChange: (patch: Partial<ChartSpec>) => void;
}

// Read/patch a config key: a first-class ChartSpec field when one exists, else
// the free-form `options` bag — so a new chart type's new option needs no
// ChartSpec change to round-trip.
function readField(chart: ChartSpec, key: string): unknown {
  if (key in chart) return (chart as unknown as Record<string, unknown>)[key];
  return chart.options?.[key];
}
// First-class ChartSpec fields that may be ABSENT on a chart loaded from an older
// saved report (added after that report was written). They must still patch the
// top-level field, not the free-form options bag.
const FIRST_CLASS_KEYS = new Set(["percent_base"]);

function patchField(
  chart: ChartSpec,
  key: string,
  value: unknown
): Partial<ChartSpec> {
  if ((key in chart || FIRST_CLASS_KEYS.has(key)) && key !== "options") {
    return { [key]: value } as Partial<ChartSpec>;
  }
  return { options: { ...(chart.options ?? {}), [key]: value } };
}

function SelectWidget({ field, chart, onChange }: WidgetProps) {
  const opts = field.options ?? [];
  const items = Object.fromEntries(opts.map((o) => [o.value, o.label]));
  const value = String(
    readField(chart, field.key) ?? field.default ?? opts[0]?.value ?? ""
  );
  return (
    <Field label={field.label} hint={field.help}>
      <Select
        items={items}
        value={value}
        onValueChange={(v) => onChange(patchField(chart, field.key, v))}
      >
        <SelectTrigger className="w-full">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {opts.map((o) => (
            <SelectItem key={o.value} value={o.value}>
              {o.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </Field>
  );
}

// Cross-tab percentage DIRECTION control. The engine values stay
// question/classifier/total/auto, but the labels NAME the actual variables so the
// analyst picks the grouping they want ("% within each Sukupuoli") without needing to
// know which variable is the internal base vs classifier. `question` distributes within
// each base category (→ each base group sums to 100 %); `classifier` within each
// classifier group. Variable-named labels only when a single classifier is set and the
// labels are loaded; otherwise the plugin's static labels. (spec 2026-07-10)
const PCT_DIRECTION_HINT =
  "“% within each X” means each X’s bars add up to 100 %.";

function shortVarLabel(label: string | undefined, name: string): string {
  const t = (label || "").replace(/\s+/g, " ").trim() || name;
  return t.length > 24 ? t.slice(0, 23) + "…" : t;
}

function PercentBaseWidget({ field, chart, question, variables, onChange }: WidgetProps) {
  // The percentage DIRECTION only applies to the % statistic on a classified chart.
  // When it doesn't apply, keep an empty grid cell (right of "Statistic") so nothing
  // else re-lays-out.
  if (chart.statistic !== "pct" || !chart.classifying_var) {
    return <div aria-hidden />;
  }
  const byName = new Map((variables ?? []).map((v) => [v.name, v]));
  const baseVar = question ? byName.get(question.variables?.[0] ?? "") : undefined;
  const clfVar = chart.classifying_var ? byName.get(chart.classifying_var) : undefined;
  // Name the variables only for a single-classifier chart with labels loaded — a second
  // classifier makes the "classifier" side a combination, so keep static labels there.
  const useNamed =
    (variables?.length ?? 0) > 0 && !!baseVar && !!clfVar && !chart.classifying_var_2;
  const opts: [string, string][] = useNamed
    ? [
        ["auto", "Automatic"],
        ["question", `% within each ${shortVarLabel(baseVar!.label, baseVar!.name)}`],
        ["classifier", `% within each ${shortVarLabel(clfVar!.label, clfVar!.name)}`],
        ["total", "% of the total"],
      ]
    : (field.options ?? []).map((o) => [o.value, o.label]);
  const value = String(chart.percent_base ?? field.default ?? "auto");
  const items = Object.fromEntries(opts);
  return (
    <Field label={field.label} hint={useNamed ? PCT_DIRECTION_HINT : field.help}>
      <Select
        items={items}
        value={value}
        onValueChange={(v) => onChange({ percent_base: v } as Partial<ChartSpec>)}
      >
        <SelectTrigger className="w-full">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {opts.map(([v, l]) => (
            <SelectItem key={v} value={v}>
              {l}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </Field>
  );
}

function SwitchWidget({ field, chart, onChange }: WidgetProps) {
  const checked = Boolean(readField(chart, field.key) ?? field.default ?? false);
  return (
    <Field label={field.label}>
      <div className="flex h-8 items-center">
        <Switch
          checked={checked}
          onCheckedChange={(c: boolean) =>
            onChange(patchField(chart, field.key, c))
          }
        />
      </div>
    </Field>
  );
}

// A "good" classifying (segmentation) variable is a low-cardinality categorical
// — gender, age group, region, experience — not a scale, free text, or a
// high-cardinality list. Keep the chart's own variable(s) selectable-by-value
// even if filtered, so an existing pick is never hidden.
function isSegmenter(v: Variable): boolean {
  // Prefer the backend's meaningful-classifier flag (excludes Likert rating
  // items, keeps demographic/segment categoricals). Fall back to a cardinality
  // heuristic only when the flag is absent (older payloads).
  if (typeof v.segmentable === "boolean") return v.segmentable;
  const n = v.n_values ?? 0;
  return v.measurement === "categorical" && n >= 2 && n <= 15;
}

function ClassifyingVarWidget({ field, chart, variables, onChange }: WidgetProps) {
  // Generic over the field key so it drives BOTH the primary classifying_var and
  // the secondary classifying_var_2 (cross-tab).
  const key = field.key as "classifying_var" | "classifying_var_2";
  const current = (chart[key] as string | null | undefined) ?? null;
  const other =
    key === "classifying_var_2" ? chart.classifying_var : chart.classifying_var_2 ?? null;
  const required = !!field.required;
  const missing = required && !current;
  const candidates = (variables ?? []).filter(
    (v) => (isSegmenter(v) || v.name === current) && v.name !== other
  );
  const items: Record<string, string> = {
    __none__: "None",
    ...Object.fromEntries(candidates.map((v) => [v.name, v.label])),
  };
  return (
    <Field
      label={field.label}
      required={required}
      hint={missing ? "This chart needs a dimension to split by" : undefined}
    >
      <Select
        items={items}
        value={current ?? "__none__"}
        onValueChange={(v) =>
          onChange({ [key]: v === "__none__" ? null : v } as Partial<ChartSpec>)
        }
      >
        <SelectTrigger className={cn("w-full", missing && "border-destructive")}>
          <SelectValue placeholder="None" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="__none__">None</SelectItem>
          {candidates.map((v) => (
            <SelectItem key={v.name} value={v.name}>
              {v.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
      {key === "classifying_var_2" && current && chart.classifying_var && (
        <button
          type="button"
          className="mt-1 text-left text-xs text-muted-foreground underline underline-offset-2 hover:text-foreground"
          onClick={() =>
            onChange({
              classifying_var: current,
              classifying_var_2: chart.classifying_var,
            } as Partial<ChartSpec>)
          }
        >
          ⇄ Swap — make the other variable the primary (outer) grouping
        </button>
      )}
      {field.help && (
        <p className="text-xs leading-snug text-muted-foreground">{field.help}</p>
      )}
    </Field>
  );
}

function SortWidget({ field, chart, onChange }: WidgetProps) {
  const opts = field.options ?? [];
  const items = Object.fromEntries(opts.map((o) => [o.value, o.label]));
  const dirDisabled = chart.sort.basis === "data_order";
  return (
    <>
      <Field label={field.label}>
        <Select
          items={items}
          value={chart.sort.basis}
          onValueChange={(v) =>
            onChange({
              sort: { ...chart.sort, basis: v as ChartSpec["sort"]["basis"] },
            })
          }
        >
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {opts.map((o) => (
              <SelectItem key={o.value} value={o.value}>
                {o.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </Field>

      {/* Sort direction — separate control; descending is the default. Not
          applicable to "Data order" (keeps the source order as-is). */}
      <Field label="Sort direction">
        <Select
          items={Object.fromEntries(SORT_DIRECTIONS.map((s) => [s.id, s.label]))}
          value={chart.sort.descending ? "desc" : "asc"}
          onValueChange={(v) =>
            onChange({ sort: { ...chart.sort, descending: v === "desc" } })
          }
          disabled={dirDisabled}
        >
          <SelectTrigger className="w-full" disabled={dirDisabled}>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {SORT_DIRECTIONS.map((s) => (
              <SelectItem key={s.id} value={s.id}>
                {s.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </Field>
    </>
  );
}

function NumberFormatWidget({ field, chart, onChange }: WidgetProps) {
  const manual = chart.number_format.mode === "manual";
  return (
    <>
      <Field label={field.label}>
        <Select
          items={NUMBER_FORMAT_ITEMS}
          value={chart.number_format.mode}
          onValueChange={(v) =>
            onChange({
              number_format: {
                ...chart.number_format,
                mode: v as "auto" | "manual",
              },
            })
          }
        >
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="auto">Auto</SelectItem>
            <SelectItem value="manual">Manual</SelectItem>
          </SelectContent>
        </Select>
      </Field>

      {manual && (
        <div className="col-span-2 grid grid-cols-3 items-end gap-4 rounded-lg border bg-muted/30 p-3">
          <Field label="% decimals">
            <Input
              type="number"
              min={0}
              max={4}
              value={chart.number_format.pct_decimals}
              onChange={(e) =>
                onChange({
                  number_format: {
                    ...chart.number_format,
                    pct_decimals: Number(e.target.value) || 0,
                  },
                })
              }
            />
          </Field>
          <Field label="Mean decimals">
            <Input
              type="number"
              min={0}
              max={4}
              value={chart.number_format.mean_decimals}
              onChange={(e) =>
                onChange({
                  number_format: {
                    ...chart.number_format,
                    mean_decimals: Number(e.target.value) || 0,
                  },
                })
              }
            />
          </Field>
          <Field label="% sign">
            <div className="flex h-8 items-center">
              <Switch
                checked={chart.number_format.show_pct_sign}
                onCheckedChange={(c: boolean) =>
                  onChange({
                    number_format: { ...chart.number_format, show_pct_sign: c },
                  })
                }
              />
            </div>
          </Field>
        </div>
      )}
    </>
  );
}

function NoteWidget({ field }: WidgetProps) {
  return (
    <div className="col-span-2 rounded-lg border border-dashed bg-muted/30 px-4 py-3 text-sm text-muted-foreground">
      {field.help}
    </div>
  );
}

// Picker for a compatible numeric/rating secondary variable (combo line). Only
// aggregatable variables are offered, guaranteeing a meaningful mean per category.
function NumericVarWidget({ field, chart, variables, onChange }: WidgetProps) {
  const current = (readField(chart, field.key) as string | null) ?? null;
  const candidates = (variables ?? []).filter(
    (v) => v.aggregatable || v.name === current
  );
  return (
    <Field label={field.label} hint={field.help ?? undefined}>
      <Select
        items={{
          __none__: "None",
          ...Object.fromEntries(candidates.map((v) => [v.name, v.label])),
        }}
        value={current ?? "__none__"}
        onValueChange={(v) =>
          onChange(patchField(chart, field.key, v === "__none__" ? null : v))
        }
      >
        <SelectTrigger className="w-full">
          <SelectValue placeholder="None" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="__none__">None</SelectItem>
          {candidates.map((v) => (
            <SelectItem key={v.name} value={v.name}>
              {v.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </Field>
  );
}

// Dispatch a schema field to its widget. Unknown widget types are skipped so an
// older UI degrades gracefully against a newer schema.
function FieldWidget(props: WidgetProps) {
  const { field, question, chart, materialId, onChange } = props;
  switch (field.widget) {
    case "select":
      // The cross-tab direction control names the actual variables so the analyst
      // picks the grouping they want without knowing base/classifier roles.
      if (field.key === "percent_base") return <PercentBaseWidget {...props} />;
      return <SelectWidget {...props} />;
    case "switch":
      return <SwitchWidget {...props} />;
    case "variable":
      return <ClassifyingVarWidget {...props} />;
    case "numeric_variable":
      return <NumericVarWidget {...props} />;
    case "sort":
      return <SortWidget {...props} />;
    case "number_format":
      return <NumberFormatWidget {...props} />;
    case "note":
      return <NoteWidget {...props} />;
    case "text":
      return <TextWidget {...props} />;
    case "not_answered":
      // Single categorical only — self-hides otherwise.
      if (!(question && (question.values?.length ?? 0) > 0)) return null;
      // The row-summary "sum"/"net" pickers reuse this widget type but bind to
      // their OWN ChartSpec field (row_summary_codes/pos/neg), not not_answered_codes.
      if (field.key.startsWith("row_summary_")) {
        return (
          <div className="col-span-2">
            <CodeMultiPicker field={field} chart={chart} question={question} onChange={onChange} />
          </div>
        );
      }
      return (
        <div className="col-span-2">
          <NotAnsweredPicker chart={chart} question={question} onChange={onChange} />
        </div>
      );
    case "category_labels":
      if (!(question && (question.category_labels?.length ?? 0) > 0)) return null;
      return (
        <div className="col-span-2">
          <CategoryLabelEditor
            chart={chart}
            question={question}
            materialId={materialId}
            onChange={onChange}
          />
        </div>
      );
    default:
      return null;
  }
}

function ConfigForm({
  schema,
  chart,
  materialId,
  question,
  variables,
  onChange,
}: {
  schema: ConfigField[];
  chart: ChartSpec;
  materialId: string;
  question: Question | undefined;
  variables: Variable[] | undefined;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  // Two columns at the Design page's wider config width: simple fields sit
  // two-across; complex widgets (number format, not-answered, category labels)
  // already declare `col-span-2` so they span the full width.
  return (
    <div className="grid grid-cols-2 items-start gap-4">
      {schema.map((field, i) => (
        <FieldWidget
          key={`${field.key}-${i}`}
          field={field}
          chart={chart}
          materialId={materialId}
          question={question}
          variables={variables}
          onChange={onChange}
        />
      ))}
    </div>
  );
}

// ── Controls for the active chart (schema-driven) ───────────────────────────
function ChartControls({
  chart,
  materialId,
  question,
  onChange,
}: {
  chart: ChartSpec;
  materialId: string;
  question: Question | undefined;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  const { data: variables } = useVariables(materialId);
  const { data: chartTypes } = useChartTypes();

  const catalog = useMemo(
    () => new Map((chartTypes ?? []).map((c) => [c.id, c])),
    [chartTypes]
  );
  const rawSchema = catalog.get(chart.chart_type)?.config ?? [];
  // A battery is already a single-series chart (one bar per attribute), so a
  // classifying split doesn't apply — drop that field for battery questions.
  const isBattery = question?.kind === "battery";
  let schema = isBattery
    ? rawSchema.filter((f) => f.key !== "classifying_var")
    : rawSchema;
  // The second classifier and the "Total column" control only make sense once a
  // classifying variable is chosen — without one there is no Total to toggle.
  // (percent_base stays in the schema even when it doesn't apply — PercentBaseWidget
  //  renders an empty placeholder so the "Statistic" row keeps its layout.)
  if (!chart.classifying_var) {
    schema = schema.filter(
      (f) => f.key !== "classifying_var_2" && f.key !== "show_total"
    );
  }
  // The two-variable LAYOUT control only applies once there are two classifiers.
  if (!chart.classifying_var_2) {
    schema = schema.filter((f) => f.key !== "xtab_layout");
  }
  // Row-summary sub-fields depend on the chosen function (the whole group is only
  // present in the stacked_horizontal_bar schema, so it never shows on other types):
  // the header once a function is picked; each code picker only for its function.
  const rsFn = chart.row_summary_fn ?? "none";
  schema = schema.filter((f) => {
    if (f.key === "row_summary_label") return rsFn !== "none";
    if (f.key === "row_summary_codes") return rsFn === "sum";
    if (f.key === "row_summary_pos_codes" || f.key === "row_summary_neg_codes")
      return rsFn === "net";
    return true;
  });
  const supportsClassifying = (typeId: string) =>
    (catalog.get(typeId)?.config ?? []).some((f) => f.key === "classifying_var");

  // Switching to a chart type with no classifying variable (e.g. a single-series
  // pie) drops any stale classifying_var, so it can't silently split the data
  // into series the chart can't show.
  const supportsClassifying2 = (typeId: string) =>
    (catalog.get(typeId)?.config ?? []).some((f) => f.key === "classifying_var_2");
  const handleTypeChange = (patch: Partial<ChartSpec>) => {
    const extra: Partial<ChartSpec> = {};
    if (patch.chart_type && !supportsClassifying(patch.chart_type) && chart.classifying_var) {
      extra.classifying_var = null;
    }
    // Dropping to a chart type without a 2nd classifier clears the cross-tab.
    if (patch.chart_type && !supportsClassifying2(patch.chart_type) && chart.classifying_var_2) {
      extra.classifying_var_2 = null;
    }
    onChange({ ...patch, ...extra });
  };

  return (
    <div className="space-y-4">
      <ChartTypeField chart={chart} question={question} onChange={handleTypeChange} />
      <SlideTitleField
        chart={chart}
        materialId={materialId}
        questionText={question?.text ?? chart.question_ref}
        onChange={onChange}
      />
      <SubtitleField
        chart={chart}
        questionText={question?.text ?? chart.question_ref}
        onChange={onChange}
      />
      <FooterNoteField chart={chart} onChange={onChange} />
      <ConfigForm
        schema={schema}
        chart={chart}
        materialId={materialId}
        question={question}
        variables={variables}
        onChange={onChange}
      />
    </div>
  );
}

// ── Editable slide title (headline) — editable right here in Design ──────────
function SlideTitleField({
  chart,
  questionText,
  onChange,
}: {
  chart: ChartSpec;
  materialId: string;
  questionText: string;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  return (
    <Field label="Slide title">
      <Textarea
        value={chart.slide_title ?? ""}
        placeholder={questionText}
        rows={3}
        className="resize-y"
        onChange={(e) => onChange({ slide_title: e.target.value })}
      />
      <p className="text-xs text-muted-foreground">
        The headline shown on the slide. Leave blank to use the question text; press
        Enter to break it onto up to three lines. The preview updates live.
      </p>
    </Field>
  );
}

// ── Editable subtitle (the question line shown just above the chart) ──────────
function SubtitleField({
  chart,
  questionText,
  onChange,
}: {
  chart: ChartSpec;
  questionText: string;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  return (
    <Field label="Subtitle">
      <Textarea
        value={chart.slide_description ?? questionText}
        rows={2}
        className="resize-y"
        onChange={(e) => onChange({ slide_description: e.target.value || null })}
      />
      <p className="text-xs text-muted-foreground">
        The question line shown just above the chart. Defaults to the question text; edits
        are saved to this report only — they don’t rename the question.
      </p>
    </Field>
  );
}

// ── Editable methodology footer (the N notation at the slide's bottom-left) ───
function FooterNoteField({
  chart,
  onChange,
}: {
  chart: ChartSpec;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  return (
    <Field label="Footer / N notation">
      <Input
        value={chart.footer_note ?? "N = {n}"}
        onChange={(e) => onChange({ footer_note: e.target.value || null })}
      />
      <p className="text-xs text-muted-foreground">
        The methodology line at the bottom-left of the slide. <code>{"{n}"}</code> = the
        respondent count, <code>{"{stat}"}</code> = the statistic label — e.g.{" "}
        <code>{"{stat} · n = {n}"}</code> → “Osuus vastaajista (%) · n = 950”.
      </p>
    </Field>
  );
}

// ── "Not answered" value picker ─────────────────────────────────────────────
function NotAnsweredPicker({
  chart,
  question,
  onChange,
}: {
  chart: ChartSpec;
  question: Question;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  const detected = useMemo(
    () => (question.missing_values ?? []).map((m) => m.code),
    [question.missing_values]
  );
  // null = "use detected": fall back to the SAV-detected missing set for display.
  const usingDetected = chart.not_answered_codes === null;
  const checked = useMemo(
    () => new Set(chart.not_answered_codes ?? detected),
    [chart.not_answered_codes, detected]
  );
  const values = question.values ?? [];

  const toggle = (code: number) => {
    const next = new Set(checked);
    if (next.has(code)) next.delete(code);
    else next.add(code);
    // Once the user edits, write the explicit list (even if it equals detected).
    onChange({ not_answered_codes: Array.from(next) });
  };

  if (values.length === 0) return null;

  return (
    <div className="space-y-2 rounded-lg border bg-muted/30 p-3">
      <div className="flex items-center justify-between gap-2">
        <Label className="text-xs font-medium text-muted-foreground">
          "Not answered" values
        </Label>
        {!usingDetected && (
          <Button
            variant="ghost"
            size="sm"
            className="h-6 px-2 text-xs text-muted-foreground"
            onClick={() => onChange({ not_answered_codes: null })}
          >
            <RotateCcwIcon className="size-3" />
            Reset to detected
          </Button>
        )}
      </div>
      <div className="max-h-36 space-y-0.5 overflow-y-auto">
        {values.map((v) => (
          <label
            key={v.code}
            className="flex cursor-pointer items-center gap-2 rounded-md px-1.5 py-1 text-sm hover:bg-muted/60"
          >
            <input
              type="checkbox"
              className="size-4 accent-primary"
              checked={checked.has(v.code)}
              onChange={() => toggle(v.code)}
            />
            <span className="tabular-nums text-muted-foreground">
              {v.code}
            </span>
            <span className="min-w-0 flex-1 truncate">{v.label}</span>
          </label>
        ))}
      </div>
      <p className="text-xs text-muted-foreground">
        Choose which answers count as "Not answered". Defaults to the values
        flagged missing in the data.
      </p>
    </div>
  );
}

// ── Generic text field (schema widget "text") ───────────────────────────────
// Binds to field.key. For the row-summary header the placeholder shows the
// function's default label so an empty field still previews sensibly.
function TextWidget({ field, chart, onChange }: WidgetProps) {
  const value = (chart as unknown as Record<string, unknown>)[field.key];
  const placeholder =
    field.key === "row_summary_label" ? defaultRowSummaryLabel(chart.row_summary_fn) : "";
  return (
    <Field label={field.label}>
      <Input
        value={(value as string) ?? ""}
        placeholder={placeholder}
        onChange={(e) => onChange({ [field.key]: e.target.value } as Partial<ChartSpec>)}
      />
    </Field>
  );
}

// ── Multi-select of the scale's value codes, bound to field.key ─────────────
// Used by the row-summary "Summed codes" / "Positive codes" / "Negative codes"
// pickers. Same look as NotAnsweredPicker but writes its own field (no detected
// fallback — the default is an empty selection).
function CodeMultiPicker({
  field,
  chart,
  question,
  onChange,
}: {
  field: ConfigField;
  chart: ChartSpec;
  question: Question;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  const values = question.values ?? [];
  const current =
    ((chart as unknown as Record<string, unknown>)[field.key] as number[] | undefined) ?? [];
  const checked = useMemo(() => new Set(current), [current]);
  const toggle = (code: number) => {
    const next = new Set(checked);
    if (next.has(code)) next.delete(code);
    else next.add(code);
    onChange({ [field.key]: Array.from(next) } as Partial<ChartSpec>);
  };
  if (values.length === 0) return null;
  return (
    <div className="space-y-2 rounded-lg border bg-muted/30 p-3">
      <Label className="text-xs font-medium text-muted-foreground">{field.label}</Label>
      <div className="max-h-36 space-y-0.5 overflow-y-auto">
        {values.map((v) => (
          <label
            key={v.code}
            className="flex cursor-pointer items-center gap-2 rounded-md px-1.5 py-1 text-sm hover:bg-muted/60"
          >
            <input
              type="checkbox"
              className="size-4 accent-primary"
              checked={checked.has(v.code)}
              onChange={() => toggle(v.code)}
            />
            <span className="tabular-nums text-muted-foreground">{v.code}</span>
            <span className="min-w-0 flex-1 truncate">{v.label}</span>
          </label>
        ))}
      </div>
    </div>
  );
}

// A label-override text field with LOCAL state, committing to the report on
// blur/Enter. Typing stays local so the heavy per-keystroke re-render cascade
// (preview re-fetch, draft update) can't steal focus or reset the cursor.
function LabelOverrideInput({
  full,
  value,
  onCommit,
}: {
  full: string;
  value: string;
  onCommit: (v: string) => void;
}) {
  const [local, setLocal] = useState(value);
  const focused = useRef(false);
  // Sync external changes (e.g. "Shorten with AI" rewrites all) only when the
  // user isn't actively editing this field.
  useEffect(() => {
    if (!focused.current) setLocal(value);
  }, [value]);
  return (
    <Input
      value={local}
      placeholder={full}
      className="h-8"
      onFocus={() => {
        focused.current = true;
      }}
      onChange={(e) => setLocal(e.target.value)}
      onBlur={() => {
        focused.current = false;
        if (local !== value) onCommit(local);
      }}
      onKeyDown={(e) => {
        if (e.key === "Enter") (e.target as HTMLInputElement).blur();
      }}
    />
  );
}

// ── Category-label editor (editable short labels + Shorten with AI) ──────────
function CategoryLabelEditor({
  chart,
  question,
  materialId,
  onChange,
}: {
  chart: ChartSpec;
  question: Question;
  materialId: string;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  const [shortening, setShortening] = useState(false);

  const overrideMap = useMemo(() => {
    const m = new Map<string, string>();
    for (const [full, short] of chart.category_label_overrides) m.set(full, short);
    return m;
  }, [chart.category_label_overrides]);

  // Write/update a single [full, short] override; empty or == full removes it.
  const setOverride = (full: string, short: string) => {
    const trimmed = short.trim();
    const pairs = chart.category_label_overrides.filter(([f]) => f !== full);
    if (trimmed && trimmed !== full) pairs.push([full, short]);
    onChange({ category_label_overrides: pairs });
  };

  const shortenWithAI = async () => {
    setShortening(true);
    try {
      const { overrides } = await api.materials.aiShortLabels(materialId, {
        question_ref: chart.question_ref,
      });
      // Keep only meaningful shortenings (non-empty, actually shorter/different).
      const useful = overrides.filter(
        ([full, short]) => short.trim() && short.trim() !== full
      );
      if (useful.length === 0) {
        toast.warning("AI couldn't shorten the labels (service may be unavailable)");
        return;
      }
      onChange({ category_label_overrides: useful });
      toast.success(`Shortened ${useful.length} label(s) with AI`);
    } catch (e) {
      toast.error(
        `Shorten with AI failed: ${e instanceof Error ? e.message : "unknown error"}`
      );
    } finally {
      setShortening(false);
    }
  };

  return (
    <div className="space-y-2 rounded-lg border bg-muted/30 p-3">
      <div className="flex items-center justify-between gap-2">
        <Label className="text-xs font-medium text-muted-foreground">
          Category labels
        </Label>
        <Button
          variant="outline"
          size="sm"
          className="h-7 px-2.5 text-xs"
          disabled={shortening}
          onClick={shortenWithAI}
        >
          {shortening ? (
            <Loader2Icon className="size-3.5 animate-spin" />
          ) : (
            <SparklesIcon className="size-3.5" />
          )}
          {shortening ? "Shortening…" : "Shorten with AI"}
        </Button>
      </div>
      <div className="max-h-64 space-y-1.5 overflow-y-auto pr-1">
        {(question.category_labels ?? []).map((full, i) => (
          <LabelOverrideInput
            key={`${full}-${i}`}
            full={full}
            value={overrideMap.get(full) ?? full}
            onCommit={(v) => setOverride(full, v)}
          />
        ))}
      </div>
      <p className="text-xs text-muted-foreground">
        The label shown in the chart for each category — edit to shorten, or let AI shorten
        them all. Restoring the full label removes the override.
      </p>
    </div>
  );
}

function ChartTypeField({
  chart,
  question,
  onChange,
}: {
  chart: ChartSpec;
  question: Question | undefined;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  // The backend tells us which chart types are compatible with this question
  // (e.g. excludes pie/doughnut for multi-response). Gray out the rest. When we
  // have no list (question still loading), keep everything selectable.
  const compatible = useMemo(() => {
    const list = question?.compatible_chart_types;
    return list && list.length > 0 ? new Set(list) : null;
  }, [question?.compatible_chart_types]);

  return (
    <Field label="Chart type">
      <Select
        items={CHART_TYPE_ITEMS}
        value={chart.chart_type}
        onValueChange={(v) => onChange({ chart_type: (v as string) ?? "" })}
      >
        <SelectTrigger className="w-full">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {CHART_TYPES.map((t) => {
            // Always keep the currently-selected type selectable, even if an old
            // report picked an incompatible one — don't trap the user.
            const incompatible =
              compatible !== null &&
              !compatible.has(t.id) &&
              t.id !== chart.chart_type;
            return (
              <SelectItem key={t.id} value={t.id} disabled={incompatible}>
                {t.label}
              </SelectItem>
            );
          })}
        </SelectContent>
      </Select>
    </Field>
  );
}

// ── Special-slide preview (full PNG; no title overlay / label region) ────────
function SpecialPreview({
  materialId,
  chart,
  bulletsPending,
}: {
  materialId: string;
  chart: ChartSpec;
  bulletsPending: boolean;
}) {
  // The whole slide (heading + bullets) is baked server-side → render the full
  // PNG (renderTitle:true) and show it plainly.
  const grouping = useContext(GroupingCtx);
  const { data: url, error: qError, isFetching: loading } = useChartPreview(
    materialId,
    chart,
    { renderTitle: true, priority: true, grouping }
  );
  const error =
    qError instanceof Error ? qError.message : qError ? "Preview failed" : null;
  return (
    // Full-width, no padding — the border frames the slide; height follows the
    // slide's aspect ratio. (SLIDE_ASPECT)
    <div className={`relative w-full overflow-hidden rounded-lg border bg-muted/30 ${SLIDE_ASPECT}`}>
        {url ? (
          <img
            src={url}
            alt="Slide preview"
            className="absolute inset-0 size-full object-contain"
          />
        ) : (
          !error && (
            <div className="flex size-full flex-col items-center justify-center gap-3 text-muted-foreground">
              <ImageIcon className="size-8 opacity-40" />
              <span className="text-sm">Rendering preview…</span>
            </div>
          )
        )}
        {url && bulletsPending && (
          <PendingRegion
            style={{ left: "6%", top: "26%", width: "88%", height: "62%" }}
            label="Generating…"
          />
        )}
        {loading && url && (
          <div className="absolute inset-0 z-20 flex items-center justify-center">
            <div className="flex items-center gap-2.5 rounded-full bg-background/95 px-5 py-2.5 text-sm font-semibold text-foreground shadow-lg ring-1 ring-border backdrop-blur-sm">
              <div className="size-4 animate-spin rounded-full border-2 border-primary border-t-transparent" />
              Updating…
            </div>
          </div>
        )}
        {error && (
          <div className="absolute inset-x-4 bottom-4 z-20 flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive shadow-sm">
            <AlertCircleIcon className="mt-0.5 size-4 shrink-0" />
            <span className="leading-snug">{error}</span>
          </div>
        )}
    </div>
  );
}

// ── Special-slide controls: editable heading + bullets + Regenerate ──────────
// Present stored bullets as editable Markdown: ensure every line shows a "*"
// marker (legacy AI bullets are plain), preserving any existing indent/marker so
// nesting round-trips. The renderer parses the same "*"/indent convention.
function bulletsToMarkdown(bullets: string[]): string {
  return bullets
    .map((b) => {
      const m = /^(\s*)([-*+]\s+)?(.*)$/.exec(b);
      const indent = m?.[1] ?? "";
      const marker = m?.[2] ?? "* ";
      const rest = m?.[3] ?? b;
      return rest.trim() ? `${indent}${marker}${rest}` : "";
    })
    .filter((l) => l !== "")
    .join("\n");
}

function SpecialSlideControls({
  chart,
  pending,
  onChange,
  onRegenerate,
}: {
  chart: ChartSpec;
  pending: boolean;
  onChange: (patch: Partial<ChartSpec>) => void;
  onRegenerate: () => void;
}) {
  const bullets = bulletsToMarkdown(
    (chart.options?.bullets as string[] | undefined) ?? []
  );
  const [draft, setDraft] = useState(bullets);
  const focused = useRef(false);
  // Resync when the generated bullets land (or when switching slides) — but NOT
  // while the user is actively editing, so an incoming (re)generation never
  // clobbers unsaved edits mid-type.
  useEffect(() => {
    if (!focused.current) setDraft(bullets);
  }, [bullets]);

  const commit = () => {
    focused.current = false;
    // Preserve leading whitespace (nesting) and the "*" marker; only trailing
    // spaces and blank lines are dropped. The renderer parses "*"/indent per line.
    const next = draft
      .split("\n")
      .map((l) => l.replace(/\s+$/, ""))
      .filter((l) => l.trim().length > 0);
    onChange({ options: { ...(chart.options ?? {}), bullets: next } });
  };

  return (
    <div className="space-y-4">
      <Field label="Heading">
        <LabelOverrideInput
          full="Slide heading"
          value={chart.slide_title ?? ""}
          onCommit={(v) => onChange({ slide_title: v || null })}
        />
      </Field>
      <Field
        label="Bullets"
        hint="Markdown: one bullet per line starting with *. Indent two spaces to nest."
      >
        <textarea
          className="min-h-72 w-full resize-y rounded-md border bg-background px-3 py-2 font-mono text-sm leading-relaxed shadow-sm focus:ring-2 focus:ring-primary/30 focus:outline-none"
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onBlur={commit}
          placeholder={
            pending
              ? "Generating…"
              : "* First point\n* Second point\n  * A nested detail"
          }
        />
      </Field>
      <Button variant="outline" size="sm" disabled={pending} onClick={onRegenerate}>
        {pending ? (
          <Loader2Icon className="size-4 animate-spin" />
        ) : (
          <SparklesIcon className="size-4" />
        )}
        Regenerate
      </Button>
    </div>
  );
}

// ── Main Configure step ─────────────────────────────────────────────────────
// Warm ONE slide's preview into the shared cache (renders nothing).
function PrefetchOne({
  materialId,
  chart,
}: {
  materialId: string;
  chart: ChartSpec;
}) {
  const grouping = useContext(GroupingCtx);
  // Warm the full-slide preview (renderTitle:true) — used by BOTH the Design
  // preview and the Overview grid — so nothing waits on focus.
  useChartPreview(materialId, chart, { renderTitle: true, enabled: true, grouping });
  return null;
}

// Lazily render EVERY slide's preview in the background so the whole deck is
// ready without the user clicking each slide one by one. Renders nothing; the
// shared content-keyed cache + the previewChart concurrency gate keep the UI
// responsive (a few render at a time). Debounced so live edits don't spam.
function DeckPrefetch({
  materialId,
  charts,
}: {
  materialId: string;
  charts: ChartSpec[];
}) {
  const key = JSON.stringify(charts);
  const [debounced, setDebounced] = useState(charts);
  useEffect(() => {
    const h = setTimeout(() => setDebounced(charts), 400);
    return () => clearTimeout(h);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);
  return (
    <>
      {debounced.map((c, i) => (
        <PrefetchOne
          key={`${c.question_ref}-${i}`}
          materialId={materialId}
          chart={c}
        />
      ))}
    </>
  );
}

function StepConfigureInner({
  materialId,
  charts,
  grouping,
  aiPending,
  active,
  setActive,
  onReorder,
  onUpdateChart,
  onEnsureTitles,
  onRegenerateSpecial,
}: {
  materialId: string;
  charts: ChartSpec[];
  grouping: GroupingOverride;
  aiPending?: AiPendingMap;
  // The active slide (question_ref) is owned by ReportWizard so the Preview grid can
  // select a slide and jump here to edit it.
  active: string | null;
  setActive: (ref: string | null) => void;
  // Drag-reorder the report's slides in the left list (affects this report only).
  onReorder: (from: number, to: number) => void;
  onUpdateChart: (index: number, patch: Partial<ChartSpec>) => void;
  // Called with every chart's ref when Design opens so AI slide titles are
  // generated automatically in the background (batched, like the thumbnails).
  onEnsureTitles?: (refs: string[]) => void;
  // Regenerate a special (non-chart) slide's AI content. Adding/removing/reordering
  // slides lives in the Select step now — Design only edits slide CONTENT.
  onRegenerateSpecial?: (chart: ChartSpec) => void;
}) {
  const { data: questions, isError } = useRegroupedQuestions(materialId, grouping);
  const [editQid, setEditQid] = useState<string | null>(null);
  const activeRowRef = useRef<HTMLDivElement>(null);
  // Drag-reorder the slide list.
  const { dragIndex, overIndex, containerRef, itemProps } = useDragReorder(onReorder);
  // Scroll the active row into view when the selection changes (← / → or a jump
  // back from the Preview grid) so the highlighted slide is always visible.
  useEffect(() => {
    activeRowRef.current?.scrollIntoView({ block: "nearest" });
  }, [active]);

  // ↑ / ↓ (and ← / →) step to the previous / next slide instead of scrolling —
  // ignored while typing in a field. The active row auto-scrolls into view, so the
  // list never needs manual scrolling.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      const prev = e.key === "ArrowUp" || e.key === "ArrowLeft";
      const next = e.key === "ArrowDown" || e.key === "ArrowRight";
      if (!prev && !next) return;
      const el = document.activeElement as HTMLElement | null;
      if (
        el &&
        (el.tagName === "INPUT" ||
          el.tagName === "TEXTAREA" ||
          el.tagName === "SELECT" ||
          el.isContentEditable)
      )
        return;
      // Handle the key here (stop the page/list from scrolling) even at the ends.
      e.preventDefault();
      const cur = Math.max(0, charts.findIndex((c) => c.question_ref === active));
      const target = Math.max(
        0,
        Math.min(charts.length - 1, prev ? cur - 1 : cur + 1)
      );
      if (target !== cur && charts[target]) {
        setActive(charts[target].question_ref);
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [active, charts, setActive]);

  const questionMap = useMemo(() => {
    const m = new Map<string, Question>();
    (questions ?? []).forEach((q) => m.set(q.qid, q));
    return m;
  }, [questions]);

  // Auto-generate AI slide titles for every chart once Design is open (batched
  // in the background, just like the thumbnails) — not on report load, and not
  // gated on opening each chart.
  const chartRefsKey = charts.map((c) => c.question_ref).join(" ");
  useEffect(() => {
    if (charts.length) onEnsureTitles?.(charts.map((c) => c.question_ref));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [chartRefsKey, onEnsureTitles]);

  if (isError) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed py-24 text-center">
        <AlertCircleIcon className="mb-3 size-8 text-muted-foreground/50" />
        <p className="text-sm font-medium">Couldn't load this material's questions</p>
        <p className="mt-1 max-w-xs text-sm text-muted-foreground">
          It may have been removed. Re-upload the data in the Data tab.
        </p>
      </div>
    );
  }

  if (charts.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed py-24 text-center">
        <BarChart3Icon className="mb-3 size-8 text-muted-foreground/50" />
        <p className="text-sm font-medium">No slides yet</p>
        <p className="mt-1 max-w-xs text-sm text-muted-foreground">
          Go back to <span className="font-medium">Select</span> to add questions
          or a special slide. Design is where you shape each slide's content.
        </p>
      </div>
    );
  }

  const activeChart =
    charts.find((c) => c.question_ref === active) ?? charts[0];
  const activeIndex = activeChart
    ? charts.findIndex((c) => c.question_ref === activeChart.question_ref)
    : -1;
  const activeSpecial = activeChart ? rendersFullSlide(activeChart) : false;
  const activeBullets = activeChart ? rendersAsBullets(activeChart) : false;
  // A "themes" chart is an open-ended question rendered as bullets — unlike a true
  // special slide it HAS an alternative chart type (word cloud), so it keeps a
  // chart-type picker AND the bullet editor.
  const activeThemes = activeChart ? isThemes(activeChart) : false;
  const activeGrid = activeChart ? isDemographicsGrid(activeChart) : false;
  const activeBulletsPending =
    aiPending?.[activeChart?.question_ref ?? ""]?.bulletsPending ?? false;

  // Update the active chart; when the type switches TO themes with no bullets yet,
  // kick off theme-bullet generation so the slide isn't empty (a plain updateChart
  // only patches the type — nothing would generate the bullets otherwise).
  const handleChange = (patch: Partial<ChartSpec>) => {
    if (!activeChart) return;
    onUpdateChart(activeIndex, patch);
    const hasBullets = !!(activeChart.options?.bullets as string[] | undefined)?.length;
    if (patch.chart_type === "themes" && !hasBullets) {
      onRegenerateSpecial?.({ ...activeChart, ...patch });
    }
  };

  return (
    <div className="space-y-4">
      {/* Background: warm every slide's preview so the deck (and the Preview grid)
          are ready without clicking each slide (renders nothing). */}
      <DeckPrefetch materialId={materialId} charts={charts} />

      {/* Top: slide list (left) + preview (right), EQUAL HEIGHT. The list is an
          absolutely-positioned scroll area so it never grows the row — the PREVIEW
          sets the row height and the list scrolls inside it to match exactly.
          Navigation only: add / remove / reorder live in the Select step. */}
      <div className="grid grid-cols-[300px_minmax(0,1fr)] items-stretch gap-4">
        <div className="relative min-h-[16rem]">
          <div
            ref={containerRef as React.RefObject<HTMLDivElement>}
            className="absolute inset-0 space-y-1.5 overflow-y-auto pr-1"
          >
            {charts.map((c, i) => {
              const isActive = c.question_ref === active;
              return (
                <div
                  key={`${c.question_ref}-${i}`}
                  {...itemProps(i)}
                  ref={isActive ? activeRowRef : undefined}
                  className={cn(
                    "flex items-center gap-1 rounded-md transition-colors",
                    isActive ? "bg-primary/10" : "hover:bg-muted/50",
                    dragIndex === i && "opacity-40",
                    // Inset ring so the drop indicator is never clipped by the
                    // scroll container's (horizontal) overflow.
                    dragIndex !== null &&
                      overIndex === i &&
                      dragIndex !== i &&
                      "ring-2 ring-inset ring-primary"
                  )}
                >
                  <span
                    className="shrink-0 cursor-grab pl-1 text-muted-foreground/40 hover:text-muted-foreground"
                    title="Drag to reorder — affects this report only"
                  >
                    <GripVerticalIcon className="size-4" />
                  </span>
                  <button
                    onClick={() => setActive(c.question_ref)}
                    className="flex min-w-0 flex-1 items-center gap-2 py-2 pr-2 text-left outline-none focus:outline-none focus-visible:outline-none focus-visible:ring-0"
                  >
                    <span className="w-5 shrink-0 text-right text-xs tabular-nums text-muted-foreground">
                      {i + 1}
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="line-clamp-1 text-sm">{slideTitle(c, questionMap)}</span>
                      <span className="mt-0.5 block text-xs text-muted-foreground">
                        {slideSubtitle(c, questionMap)}
                      </span>
                    </span>
                  </button>
                </div>
              );
            })}
          </div>
        </div>

        {activeChart && (
          <div className="relative">
            {activeSpecial ? (
              <SpecialPreview
                key={activeChart.question_ref}
                materialId={materialId}
                chart={activeChart}
                bulletsPending={activeBulletsPending}
              />
            ) : (
              <ChartPreview
                key={activeChart.question_ref}
                materialId={materialId}
                chart={activeChart}
                titlePending={
                  aiPending?.[activeChart.question_ref]?.titlePending ?? false
                }
                labelsPending={
                  aiPending?.[activeChart.question_ref]?.labelsPending ?? false
                }
                questionText={
                  questionMap.get(activeChart.question_ref)?.text ??
                  activeChart.question_ref
                }
              />
            )}
            {/* Question details — chart slides only (special slides are edited inline). */}
            {!activeSpecial && (
              <button
                type="button"
                title="View question details"
                onClick={() => setEditQid(activeChart.question_ref)}
                className="absolute right-2 top-2 z-20 flex size-8 items-center justify-center rounded-md bg-background/85 text-muted-foreground shadow-sm ring-1 ring-border backdrop-blur-sm transition-colors hover:text-foreground"
              >
                <InfoIcon className="size-4" />
              </button>
            )}
          </div>
        )}
      </div>

      {/* Configuration — full width below the list + preview. */}
      {activeChart && (
        <div className="rounded-xl border bg-card p-4">
          {activeSpecial ? (
            activeGrid ? (
              <p className="text-sm text-muted-foreground">
                A demographics overview — the charts are chosen automatically from the
                respondent (age, gender, geography…) questions. Remove or reorder this
                slide in the Select step.
              </p>
            ) : activeThemes ? (
              // Open-ended themes: keep the chart-type picker (themes ↔ word cloud)
              // AND the bullet editor + regenerate.
              <div className="space-y-4">
                <ChartTypeField
                  chart={activeChart}
                  question={questionMap.get(activeChart.question_ref)}
                  onChange={handleChange}
                />
                <SpecialSlideControls
                  chart={activeChart}
                  pending={activeBulletsPending}
                  onChange={(patch) => onUpdateChart(activeIndex, patch)}
                  onRegenerate={() => onRegenerateSpecial?.(activeChart)}
                />
              </div>
            ) : activeBullets ? (
              <SpecialSlideControls
                chart={activeChart}
                pending={activeBulletsPending}
                onChange={(patch) => onUpdateChart(activeIndex, patch)}
                onRegenerate={() => onRegenerateSpecial?.(activeChart)}
              />
            ) : (
              <p className="text-sm text-muted-foreground">
                This slide has no options — remove it in the Select step.
              </p>
            )
          ) : (
            <ChartControls
              chart={activeChart}
              materialId={materialId}
              question={questionMap.get(activeChart.question_ref)}
              onChange={handleChange}
            />
          )}
        </div>
      )}

      <QuestionDetailsDialog
        materialId={materialId}
        qid={editQid}
        readOnly
        grouping={grouping}
        onOpenChange={(open) => {
          if (!open) setEditQid(null);
        }}
      />
    </div>
  );
}

// Provide the report's grouping to the leaf preview components (via context) so
// they don't need it prop-drilled through the whole Design tree.
export default function StepConfigure(
  props: Parameters<typeof StepConfigureInner>[0]
) {
  return (
    <GroupingCtx.Provider value={props.grouping}>
      <StepConfigureInner {...props} />
    </GroupingCtx.Provider>
  );
}
