import { useEffect, useMemo, useRef, useState } from "react";
import {
  AlertCircleIcon,
  BarChart3Icon,
  ImageIcon,
  Loader2Icon,
  RotateCcwIcon,
  SparklesIcon,
  Trash2Icon,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { api } from "@/lib/api";
import type { ChartSpec, Question } from "@/lib/api";
import { useQuestions, useVariables } from "@/lib/queries";
import {
  CHART_TYPES,
  CHART_TYPE_ITEMS,
  NUMBER_FORMAT_ITEMS,
  SORT_OPTIONS,
  SORT_ITEMS,
  STATISTICS,
  STATISTIC_ITEMS,
  chartTypeLabel,
  isStacked,
} from "@/lib/charts";

// Per-chart pending flags (keyed by question_ref) from the auto-AI orchestrator.
export type AiPendingMap = Record<
  string,
  { titlePending: boolean; labelsPending: boolean }
>;

type Region = { left: string; top: string; width: string; height: string };

// Where the category labels are baked into the rendered PNG, per chart type, so
// the "Shortening labels…" placeholder can sit over the right area. Percentages
// map onto the 4:3 image because the container is constrained to that aspect.
function labelRegion(chartType: string): Region {
  switch (chartType) {
    case "horizontal_bar":
    case "stacked_horizontal_bar":
      // Left gutter where the category labels run down the y-axis.
      return { left: "1.5%", top: "20%", width: "24%", height: "66%" };
    case "pie":
    case "doughnut":
      // Right-hand legend.
      return { left: "71%", top: "22%", width: "27.5%", height: "60%" };
    case "radar":
      // Perimeter labels — a small centered chip rather than a box.
      return { left: "37%", top: "44%", width: "26%", height: "12%" };
    default:
      // vertical_bar / stacked_vertical_bar / line / combo / funnel — x-axis.
      return { left: "6%", top: "82%", width: "88%", height: "14%" };
  }
}

// Dashed placeholder over a region still being generated by the AI.
function PendingRegion({
  style,
  label,
}: {
  style: React.CSSProperties;
  label: string;
}) {
  return (
    <div
      className="absolute z-10 flex items-center justify-center rounded-lg border-2 border-dashed border-primary/40 bg-background/65 px-2 text-center backdrop-blur-[1px]"
      style={style}
    >
      <span className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
        <SparklesIcon className="size-3.5 shrink-0 animate-pulse text-primary" />
        {label}
      </span>
    </div>
  );
}

// ── Live preview ──────────────────────────────────────────────────────────
function ChartPreview({
  materialId,
  chart,
  titlePending,
  labelsPending,
  questionText,
}: {
  materialId: string;
  chart: ChartSpec;
  titlePending: boolean;
  labelsPending: boolean;
  questionText: string;
}) {
  const [url, setUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const urlRef = useRef<string | null>(null);

  // Serialise the fields that affect the rendered image. The frontend owns the
  // title region (render_title:false), so slide_title/description are NOT
  // included — they don't change the PNG and shouldn't trigger a re-render.
  const key = useMemo(
    () =>
      JSON.stringify({
        question_ref: chart.question_ref,
        chart_type: chart.chart_type,
        statistic: chart.statistic,
        classifying_var: chart.classifying_var,
        number_format: chart.number_format,
        sort: chart.sort,
        elements: chart.elements,
        scatter_xy: chart.scatter_xy,
        show_not_answered: chart.show_not_answered,
        show_empty_categories: chart.show_empty_categories,
        not_answered_codes: chart.not_answered_codes,
        category_label_overrides: chart.category_label_overrides,
      }),
    [chart]
  );

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    const handle = setTimeout(async () => {
      try {
        // render_title:false — the PNG omits the title block; we render it as
        // the overlay headline so it can stream in independently.
        const blob = await api.materials.previewChart(materialId, chart, {
          renderTitle: false,
        });
        if (cancelled) return;
        const next = URL.createObjectURL(blob);
        if (urlRef.current) URL.revokeObjectURL(urlRef.current);
        urlRef.current = next;
        setUrl(next);
        setError(null);
      } catch (e) {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : "Preview failed");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }, 400);
    return () => {
      cancelled = true;
      clearTimeout(handle);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key, materialId]);

  // Revoke on unmount
  useEffect(
    () => () => {
      if (urlRef.current) URL.revokeObjectURL(urlRef.current);
    },
    []
  );

  const title = chart.slide_title?.trim() || questionText;
  const region = labelRegion(chart.chart_type);

  return (
    <div className="rounded-xl border bg-muted/30 p-4">
      {/* 4:3 container so percentage-based region overlays map onto the image. */}
      <div className="relative mx-auto aspect-[4/3] w-full max-w-2xl overflow-hidden rounded-lg">
        {url ? (
          <img
            src={url}
            alt="Chart preview"
            className="absolute inset-0 size-full rounded-md object-fill shadow-sm"
          />
        ) : (
          !error && (
            <div className="flex size-full flex-col items-center justify-center gap-3 text-muted-foreground">
              <ImageIcon className="size-8 opacity-40" />
              <span className="text-sm">Rendering preview…</span>
            </div>
          )
        )}

        {/* Title region (top band) — frontend-owned since render_title:false. */}
        {url &&
          (titlePending ? (
            <PendingRegion
              style={{ left: "3%", top: "2.5%", width: "70%", height: "13%" }}
              label="Generating title…"
            />
          ) : (
            <div
              className="absolute z-10 flex items-stretch gap-2.5"
              style={{ left: "3%", top: "2.5%", width: "72%", height: "13%" }}
            >
              <div className="w-1 shrink-0 rounded-full bg-teal-600" />
              <p className="line-clamp-2 text-left text-[15px] leading-tight font-bold text-foreground">
                {title}
              </p>
            </div>
          ))}

        {/* Label region — placed per chart type; clears when labels land. */}
        {url && labelsPending && (
          <PendingRegion
            style={{
              left: region.left,
              top: region.top,
              width: region.width,
              height: region.height,
            }}
            label="Shortening labels…"
          />
        )}

        {loading && (
          <div className="absolute top-3 right-3 z-20 flex items-center gap-2 rounded-full bg-background/90 px-3 py-1.5 text-xs text-muted-foreground shadow-sm ring-1 ring-border">
            <div className="size-3 animate-spin rounded-full border-2 border-primary border-t-transparent" />
            Updating…
          </div>
        )}

        {error && (
          <div className="absolute inset-x-4 bottom-4 z-20 flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive shadow-sm">
            <AlertCircleIcon className="mt-0.5 size-4 shrink-0" />
            <span className="leading-snug">{error}</span>
          </div>
        )}
      </div>
    </div>
  );
}

// ── A labelled control row ──────────────────────────────────────────────────
function Field({
  label,
  required,
  children,
  hint,
}: {
  label: string;
  required?: boolean;
  hint?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-1.5">
      <Label className="text-xs font-medium text-muted-foreground">
        {label}
        {required && <span className="ml-1 text-destructive">*</span>}
      </Label>
      {children}
      {hint && <p className="text-xs text-amber-600">{hint}</p>}
    </div>
  );
}

// ── Controls for the active chart ───────────────────────────────────────────
function ChartControls({
  chart,
  materialId,
  question,
  onChange,
}: {
  chart: ChartSpec;
  materialId: string;
  question: Question | undefined;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  const { data: variables } = useVariables(materialId);
  const stacked = isStacked(chart.chart_type);
  const isSingle = question?.kind === "single";
  const stackedMissing = stacked && !chart.classifying_var;
  const manual = chart.number_format.mode === "manual";
  const varItems: Record<string, string> = {
    __none__: "None",
    ...Object.fromEntries((variables ?? []).map((v) => [v.name, v.label])),
  };

  if (chart.chart_type === "scatter") {
    return (
      <div className="space-y-4">
        <ChartTypeField chart={chart} question={question} onChange={onChange} />
        <div className="rounded-lg border border-dashed bg-muted/30 px-4 py-3 text-sm text-muted-foreground">
          Scatter configuration coming soon.
        </div>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-2 gap-x-4 gap-y-4">
      <ChartTypeField chart={chart} question={question} onChange={onChange} />

      <Field label="Statistic">
        <Select
          items={STATISTIC_ITEMS}
          value={chart.statistic}
          onValueChange={(v) =>
            onChange({ statistic: v as ChartSpec["statistic"] })
          }
        >
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {STATISTICS.map((s) => (
              <SelectItem key={s.id} value={s.id}>
                {s.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </Field>

      <Field
        label="Classifying variable"
        required={stacked}
        hint={
          stackedMissing
            ? "Stacked charts need a dimension to split by"
            : undefined
        }
      >
        <Select
          items={varItems}
          value={chart.classifying_var ?? "__none__"}
          onValueChange={(v) =>
            onChange({ classifying_var: v === "__none__" ? null : v })
          }
        >
          <SelectTrigger
            className={cn("w-full", stackedMissing && "border-destructive")}
          >
            <SelectValue placeholder="None" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="__none__">None</SelectItem>
            {(variables ?? []).map((v) => (
              <SelectItem key={v.name} value={v.name}>
                {v.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <p className="text-xs leading-snug text-muted-foreground">
          Optional — break the chart down by another variable (e.g. by gender or
          age) to get a series per group plus a Total. Required for stacked
          charts. Leave as None for one overall result.
        </p>
      </Field>

      <Field label="Sort">
        <Select
          items={SORT_ITEMS}
          value={chart.sort.basis}
          onValueChange={(v) =>
            onChange({
              sort: {
                ...chart.sort,
                basis: v as ChartSpec["sort"]["basis"],
                descending: true,
              },
            })
          }
        >
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {SORT_OPTIONS.map((s) => (
              <SelectItem key={s.id} value={s.id}>
                {s.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </Field>

      {/* Number format */}
      <Field label="Number format">
        <Select
          items={NUMBER_FORMAT_ITEMS}
          value={chart.number_format.mode}
          onValueChange={(v) =>
            onChange({
              number_format: {
                ...chart.number_format,
                mode: v as "auto" | "manual",
              },
            })
          }
        >
          <SelectTrigger className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="auto">Auto</SelectItem>
            <SelectItem value="manual">Manual</SelectItem>
          </SelectContent>
        </Select>
      </Field>

      {/* Show "Not answered" */}
      <Field label='Show "Not answered"'>
        <div className="flex h-8 items-center">
          <Switch
            checked={chart.show_not_answered}
            onCheckedChange={(checked: boolean) =>
              onChange({ show_not_answered: checked })
            }
          />
        </div>
      </Field>

      {/* Show empty (0%) categories */}
      <Field label="Show empty (0%) categories">
        <div className="flex h-8 items-center">
          <Switch
            checked={chart.show_empty_categories}
            onCheckedChange={(checked: boolean) =>
              onChange({ show_empty_categories: checked })
            }
          />
        </div>
      </Field>

      {/* "Not answered" value picker — single categorical only */}
      {isSingle && question && (question.values?.length ?? 0) > 0 && (
        <div className="col-span-2">
          <NotAnsweredPicker
            chart={chart}
            question={question}
            onChange={onChange}
          />
        </div>
      )}

      {/* Category-label editor + Shorten with AI */}
      {question && (question.category_labels?.length ?? 0) > 0 && (
        <div className="col-span-2">
          <CategoryLabelEditor
            chart={chart}
            question={question}
            materialId={materialId}
            onChange={onChange}
          />
        </div>
      )}

      {manual && (
        <div className="col-span-2 grid grid-cols-3 items-end gap-4 rounded-lg border bg-muted/30 p-3">
          <Field label="% decimals">
            <Input
              type="number"
              min={0}
              max={4}
              value={chart.number_format.pct_decimals}
              onChange={(e) =>
                onChange({
                  number_format: {
                    ...chart.number_format,
                    pct_decimals: Number(e.target.value) || 0,
                  },
                })
              }
            />
          </Field>
          <Field label="Mean decimals">
            <Input
              type="number"
              min={0}
              max={4}
              value={chart.number_format.mean_decimals}
              onChange={(e) =>
                onChange({
                  number_format: {
                    ...chart.number_format,
                    mean_decimals: Number(e.target.value) || 0,
                  },
                })
              }
            />
          </Field>
          <Field label="% sign">
            <div className="flex h-8 items-center">
              <Switch
                checked={chart.number_format.show_pct_sign}
                onCheckedChange={(checked: boolean) =>
                  onChange({
                    number_format: {
                      ...chart.number_format,
                      show_pct_sign: checked,
                    },
                  })
                }
              />
            </div>
          </Field>
        </div>
      )}
    </div>
  );
}

// ── "Not answered" value picker ─────────────────────────────────────────────
function NotAnsweredPicker({
  chart,
  question,
  onChange,
}: {
  chart: ChartSpec;
  question: Question;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  const detected = useMemo(
    () => (question.missing_values ?? []).map((m) => m.code),
    [question.missing_values]
  );
  // null = "use detected": fall back to the SAV-detected missing set for display.
  const usingDetected = chart.not_answered_codes === null;
  const checked = useMemo(
    () => new Set(chart.not_answered_codes ?? detected),
    [chart.not_answered_codes, detected]
  );
  const values = question.values ?? [];

  const toggle = (code: number) => {
    const next = new Set(checked);
    if (next.has(code)) next.delete(code);
    else next.add(code);
    // Once the user edits, write the explicit list (even if it equals detected).
    onChange({ not_answered_codes: Array.from(next) });
  };

  if (values.length === 0) return null;

  return (
    <div className="space-y-2 rounded-lg border bg-muted/30 p-3">
      <div className="flex items-center justify-between gap-2">
        <Label className="text-xs font-medium text-muted-foreground">
          "Not answered" values
        </Label>
        {!usingDetected && (
          <Button
            variant="ghost"
            size="sm"
            className="h-6 px-2 text-xs text-muted-foreground"
            onClick={() => onChange({ not_answered_codes: null })}
          >
            <RotateCcwIcon className="size-3" />
            Reset to detected
          </Button>
        )}
      </div>
      <div className="max-h-36 space-y-0.5 overflow-y-auto">
        {values.map((v) => (
          <label
            key={v.code}
            className="flex cursor-pointer items-center gap-2 rounded-md px-1.5 py-1 text-sm hover:bg-muted/60"
          >
            <input
              type="checkbox"
              className="size-4 accent-primary"
              checked={checked.has(v.code)}
              onChange={() => toggle(v.code)}
            />
            <span className="tabular-nums text-muted-foreground">
              {v.code}
            </span>
            <span className="min-w-0 flex-1 truncate">{v.label}</span>
          </label>
        ))}
      </div>
      <p className="text-xs text-muted-foreground">
        Choose which answers count as "Not answered". Defaults to the values
        flagged missing in the data.
      </p>
    </div>
  );
}

// ── Category-label editor (editable short labels + Shorten with AI) ──────────
function CategoryLabelEditor({
  chart,
  question,
  materialId,
  onChange,
}: {
  chart: ChartSpec;
  question: Question;
  materialId: string;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  const [shortening, setShortening] = useState(false);

  const overrideMap = useMemo(() => {
    const m = new Map<string, string>();
    for (const [full, short] of chart.category_label_overrides) m.set(full, short);
    return m;
  }, [chart.category_label_overrides]);

  // Write/update a single [full, short] override; empty or == full removes it.
  const setOverride = (full: string, short: string) => {
    const trimmed = short.trim();
    const pairs = chart.category_label_overrides.filter(([f]) => f !== full);
    if (trimmed && trimmed !== full) pairs.push([full, short]);
    onChange({ category_label_overrides: pairs });
  };

  const shortenWithAI = async () => {
    setShortening(true);
    try {
      const { overrides } = await api.materials.aiShortLabels(materialId, {
        question_ref: chart.question_ref,
      });
      // Keep only meaningful shortenings (non-empty, actually shorter/different).
      const useful = overrides.filter(
        ([full, short]) => short.trim() && short.trim() !== full
      );
      if (useful.length === 0) {
        toast.warning("AI couldn't shorten the labels (service may be unavailable)");
        return;
      }
      onChange({ category_label_overrides: useful });
      toast.success(`Shortened ${useful.length} label(s) with AI`);
    } catch (e) {
      toast.error(
        `Shorten with AI failed: ${e instanceof Error ? e.message : "unknown error"}`
      );
    } finally {
      setShortening(false);
    }
  };

  return (
    <div className="space-y-2 rounded-lg border bg-muted/30 p-3">
      <div className="flex items-center justify-between gap-2">
        <Label className="text-xs font-medium text-muted-foreground">
          Category labels
        </Label>
        <Button
          variant="outline"
          size="sm"
          className="h-7 px-2.5 text-xs"
          disabled={shortening}
          onClick={shortenWithAI}
        >
          {shortening ? (
            <Loader2Icon className="size-3.5 animate-spin" />
          ) : (
            <SparklesIcon className="size-3.5" />
          )}
          {shortening ? "Shortening…" : "Shorten with AI"}
        </Button>
      </div>
      <div className="max-h-64 space-y-1.5 overflow-y-auto pr-1">
        {(question.category_labels ?? []).map((full, i) => (
          <div
            key={`${full}-${i}`}
            className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)] items-center gap-2"
          >
            <span className="text-sm leading-snug text-muted-foreground break-words">
              {full}
            </span>
            <Input
              value={overrideMap.get(full) ?? ""}
              placeholder={full}
              className="h-8"
              onChange={(e) => setOverride(full, e.target.value)}
            />
          </div>
        ))}
      </div>
      <p className="text-xs text-muted-foreground">
        Edit the short label shown in the chart, or let AI shorten them all.
        Leave blank to use the full label.
      </p>
    </div>
  );
}

function ChartTypeField({
  chart,
  question,
  onChange,
}: {
  chart: ChartSpec;
  question: Question | undefined;
  onChange: (patch: Partial<ChartSpec>) => void;
}) {
  // The backend tells us which chart types are compatible with this question
  // (e.g. excludes pie/doughnut for multi-response). Gray out the rest. When we
  // have no list (question still loading), keep everything selectable.
  const compatible = useMemo(() => {
    const list = question?.compatible_chart_types;
    return list && list.length > 0 ? new Set(list) : null;
  }, [question?.compatible_chart_types]);

  return (
    <Field label="Chart type">
      <Select
        items={CHART_TYPE_ITEMS}
        value={chart.chart_type}
        onValueChange={(v) => onChange({ chart_type: (v as string) ?? "" })}
      >
        <SelectTrigger className="w-full">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {CHART_TYPES.map((t) => {
            // Always keep the currently-selected type selectable, even if an old
            // report picked an incompatible one — don't trap the user.
            const incompatible =
              compatible !== null &&
              !compatible.has(t.id) &&
              t.id !== chart.chart_type;
            return (
              <SelectItem key={t.id} value={t.id} disabled={incompatible}>
                {t.label}
              </SelectItem>
            );
          })}
        </SelectContent>
      </Select>
    </Field>
  );
}

// ── Main Configure step ─────────────────────────────────────────────────────
export default function StepConfigure({
  materialId,
  charts,
  aiPending,
  onUpdateChart,
  onRemoveChart,
}: {
  materialId: string;
  charts: ChartSpec[];
  aiPending?: AiPendingMap;
  onUpdateChart: (index: number, patch: Partial<ChartSpec>) => void;
  onRemoveChart: (index: number) => void;
}) {
  const { data: questions, isError } = useQuestions(materialId);
  const [active, setActive] = useState(0);

  const questionMap = useMemo(() => {
    const m = new Map<string, Question>();
    (questions ?? []).forEach((q) => m.set(q.qid, q));
    return m;
  }, [questions]);

  // Keep active index valid as charts change.
  useEffect(() => {
    if (active > charts.length - 1) setActive(Math.max(0, charts.length - 1));
  }, [charts.length, active]);

  if (isError) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed py-24 text-center">
        <AlertCircleIcon className="mb-3 size-8 text-muted-foreground/50" />
        <p className="text-sm font-medium">Couldn't load this material's questions</p>
        <p className="mt-1 max-w-xs text-sm text-muted-foreground">
          It may have been removed. Re-upload the data in the Data tab.
        </p>
      </div>
    );
  }

  if (charts.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed py-24 text-center">
        <BarChart3Icon className="mb-3 size-8 text-muted-foreground/50" />
        <p className="text-sm font-medium">No charts yet</p>
        <p className="mt-1 max-w-xs text-sm text-muted-foreground">
          Go back to <span className="font-medium">Select</span> and add
          questions to configure their charts here.
        </p>
      </div>
    );
  }

  const activeChart = charts[active];

  return (
    <div className="grid grid-cols-[280px_minmax(0,1fr)] gap-6">
      {/* Left: chart list */}
      <div className="space-y-2">
        <p className="px-1 text-xs font-medium tracking-wide text-muted-foreground uppercase">
          Charts ({charts.length})
        </p>
        <div className="space-y-1.5">
          {charts.map((c, i) => {
            const q = questionMap.get(c.question_ref);
            return (
              <button
                key={`${c.question_ref}-${i}`}
                onClick={() => setActive(i)}
                className={cn(
                  "group flex w-full items-start gap-3 rounded-lg border px-3 py-2.5 text-left transition-colors",
                  i === active
                    ? "border-primary/40 bg-primary/5"
                    : "border-transparent hover:bg-muted/60"
                )}
              >
                <span
                  className={cn(
                    "mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-md text-xs font-medium tabular-nums",
                    i === active
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted text-muted-foreground"
                  )}
                >
                  {i + 1}
                </span>
                <span className="min-w-0 flex-1">
                  <span className="line-clamp-2 text-sm leading-snug">
                    {q?.text ?? c.question_ref}
                  </span>
                  <span className="mt-0.5 block text-xs text-muted-foreground">
                    {chartTypeLabel(c.chart_type)}
                  </span>
                </span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Right: large preview + compact controls */}
      {activeChart && (
        <div className="flex flex-col gap-5">
          <div className="flex items-start justify-between gap-4">
            <div className="min-w-0">
              <h3 className="truncate text-sm font-semibold">
                {questionMap.get(activeChart.question_ref)?.text ??
                  activeChart.question_ref}
              </h3>
              <p className="mt-0.5 font-mono text-xs text-muted-foreground">
                {activeChart.question_ref}
              </p>
            </div>
            <Button
              variant="ghost"
              size="sm"
              className="shrink-0 text-muted-foreground hover:text-destructive"
              onClick={() => onRemoveChart(active)}
            >
              <Trash2Icon className="size-4" />
              Remove
            </Button>
          </div>

          <ChartPreview
            key={`${activeChart.question_ref}-${active}`}
            materialId={materialId}
            chart={activeChart}
            titlePending={
              aiPending?.[activeChart.question_ref]?.titlePending ?? false
            }
            labelsPending={
              aiPending?.[activeChart.question_ref]?.labelsPending ?? false
            }
            questionText={
              questionMap.get(activeChart.question_ref)?.text ??
              activeChart.question_ref
            }
          />

          <div className="rounded-xl border bg-card p-4">
            <ChartControls
              chart={activeChart}
              materialId={materialId}
              question={questionMap.get(activeChart.question_ref)}
              onChange={(patch) => onUpdateChart(active, patch)}
            />
          </div>
        </div>
      )}
    </div>
  );
}
