#!/usr/bin/env python3
"""Build the deck's STRUCTURAL slides (title + section dividers) in nSight house style.

These are the non-data slides of a market-research deck: one TITLE slide and any
number of SECTION-DIVIDER slides. Everything is drawn with python-pptx shapes
(no chart, no external image), so the slides are crisp at any zoom.

House style:
  - 16:9 (13.333" x 7.5")
  - cream background  #F4EFE6
  - teal accent       #2F6F8F
  - ink / muted text  #2B2B2B / #6E6A63
  - font: Liberation Sans  (NOT Arial)

A single reusable `make_slide(prs, kind="title"|"divider", heading=..., ...)`
draws one slide. `build()` wires up a whole deck from a TITLE spec plus a list
of divider headings, so the structural slides of any deck can be regenerated by
changing only those parameters.
"""
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE

ROOT = Path("/home/johan/Projects/nsight/proto")

# ----------------------------------------------------------------- palette
CREAM = RGBColor(0xF4, 0xEF, 0xE6)   # background
TEAL = RGBColor(0x2F, 0x6F, 0x8F)    # accent
TEAL_DK = RGBColor(0x20, 0x52, 0x6B)  # deeper teal for the divider number
INK = RGBColor(0x2B, 0x2B, 0x2B)     # primary text
MUTED = RGBColor(0x6E, 0x6A, 0x63)   # secondary text
HAIRLINE = RGBColor(0xD9, 0xCF, 0xBE)  # subtle rule on cream

FONT = "Liberation Sans"
SW = Inches(13.333)
SH = Inches(7.5)


# ----------------------------------------------------------------- helpers
def _no_shadow(shape):
    shape.shadow.inherit = False


def _rect(slide, l, t, w, h, color, line=False):
    sp = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, l, t, w, h)
    sp.fill.solid()
    sp.fill.fore_color.rgb = color
    if line:
        sp.line.color.rgb = color
    else:
        sp.line.fill.background()
    _no_shadow(sp)
    return sp


def _send_to_back(slide, shape):
    tree = slide.shapes._spTree
    tree.remove(shape._element)
    tree.insert(2, shape._element)


def _textbox(slide, l, t, w, h, lines, *, align=PP_ALIGN.LEFT,
             anchor=MSO_ANCHOR.TOP, space_after=0, line_spacing=None):
    """lines: list of paragraphs; each paragraph is list of (text,size,color,bold,spacing)."""
    tb = slide.shapes.add_textbox(l, t, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    tf.margin_left = 0
    tf.margin_right = 0
    tf.margin_top = 0
    tf.margin_bottom = 0
    first = True
    for para in lines:
        p = tf.paragraphs[0] if first else tf.add_paragraph()
        first = False
        p.alignment = align
        p.space_after = Pt(space_after)
        p.space_before = Pt(0)
        if line_spacing is not None:
            p.line_spacing = line_spacing
        for run in para:
            txt, sz, col, bold = run[0], run[1], run[2], run[3]
            spacing = run[4] if len(run) > 4 else None
            r = p.add_run()
            r.text = txt
            r.font.size = Pt(sz)
            r.font.bold = bold
            r.font.color.rgb = col
            r.font.name = FONT
            if spacing is not None:
                # letter-spacing in 1/100 pt via XML attribute
                r.font._rPr.set("spc", str(int(spacing * 100)))
    return tb


def _add_background(slide):
    bg = _rect(slide, 0, 0, SW, SH, CREAM)
    _send_to_back(slide, bg)
    return bg


# ----------------------------------------------------------------- slide builders
def make_title_slide(prs, heading, subheading, footnote, *, brand="nSight"):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide)

    # Left teal sidebar band (full height) — strong house anchor for the cover.
    band_w = Inches(0.34)
    _rect(slide, 0, 0, band_w, SH, TEAL)

    # Brand / kicker, small caps style above the title.
    _textbox(slide, Inches(1.05), Inches(1.45), Inches(11.0), Inches(0.4),
             [[(brand.upper() + "  ·  MARKKINATUTKIMUS", 12, TEAL, True, 2.2)]])

    # Thin teal rule under the kicker.
    _rect(slide, Inches(1.07), Inches(1.92), Inches(2.3), Pt(2.4), TEAL)

    # Main title (large), split on the em-dash so the brand sits on its own line.
    if " — " in heading:
        a, b = heading.split(" — ", 1)
        title_lines = [
            [(a, 44, INK, True)],
            [(b, 44, TEAL_DK, True)],
        ]
    else:
        title_lines = [[(heading, 44, INK, True)]]
    _textbox(slide, Inches(1.05), Inches(2.35), Inches(11.3), Inches(2.1),
             title_lines, space_after=2, line_spacing=1.04)

    # Subheading (wave / date).
    _textbox(slide, Inches(1.07), Inches(4.55), Inches(10.5), Inches(0.55),
             [[(subheading, 21, MUTED, False)]])

    # Footnote pinned to lower-left, above a hairline.
    _rect(slide, Inches(1.07), Inches(6.45), Inches(5.2), Pt(1.2), HAIRLINE)
    _textbox(slide, Inches(1.07), Inches(6.60), Inches(11.0), Inches(0.5),
             [[(footnote, 11.5, MUTED, False)]])

    return slide


def make_divider_slide(prs, heading, *, index=None, total=None, kicker="OSIO"):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide)

    # Large faint section number, top-left, as a quiet design element.
    if index is not None:
        num = f"{index:02d}"
        _textbox(slide, Inches(1.0), Inches(1.55), Inches(3.0), Inches(2.4),
                 [[(num, 150, RGBColor(0xE3, 0xDA, 0xC9), True)]],
                 anchor=MSO_ANCHOR.MIDDLE)

    # Kicker label + optional progress (e.g. "OSIO 3 / 7").
    if index is not None and total is not None:
        kick = f"{kicker}  {index} / {total}"
    else:
        kick = kicker
    _textbox(slide, Inches(1.05), Inches(2.95), Inches(11.0), Inches(0.4),
             [[(kick, 13, TEAL, True, 2.4)]])

    # Short teal accent bar above the heading.
    _rect(slide, Inches(1.07), Inches(3.45), Inches(0.95), Pt(4), TEAL)

    # The section heading itself — the hero of the slide.
    _textbox(slide, Inches(1.05), Inches(3.62), Inches(11.3), Inches(2.2),
             [[(heading, 40, INK, True)]], line_spacing=1.04)

    # Footer hairline + brand tag bottom-right for consistency with the cover.
    _rect(slide, Inches(1.07), Inches(6.62), Inches(11.2), Pt(1.0), HAIRLINE)
    _textbox(slide, Inches(1.07), Inches(6.74), Inches(11.16), Inches(0.4),
             [[("nSight  ·  Attendo — Bränditutkimus", 10.5, MUTED, False)]],
             align=PP_ALIGN.LEFT)

    return slide


def make_slide(prs, kind, heading, **kw):
    """Dispatch: kind='title' or kind='divider'. Heading is the slide text."""
    if kind == "title":
        return make_title_slide(
            prs, heading,
            kw.get("subheading", ""),
            kw.get("footnote", ""),
            brand=kw.get("brand", "nSight"),
        )
    elif kind == "divider":
        return make_divider_slide(
            prs, heading,
            index=kw.get("index"),
            total=kw.get("total"),
            kicker=kw.get("kicker", "OSIO"),
        )
    raise ValueError(f"unknown slide kind: {kind!r}")


# ----------------------------------------------------------------- deck wiring
def build(
    out_path=ROOT / "work" / "agent_structural.pptx",
    *,
    title_heading="Attendo — Bränditutkimus",
    title_subheading="Marraskuu 2025",
    title_footnote="Automaattisesti tuotettu · kysely n=1001",
    sections=(
        "Tavoitteet ja tiedonkeruu",
        "Yhteenveto",
        "Tutkimustulokset",
        "Lisätietoa vastaajista",
        "Bränditietoisuus",
        "Spontaanit brändimielikuvat",
        "Halukkuus valita tai suositella",
    ),
):
    prs = Presentation()
    prs.slide_width = SW
    prs.slide_height = SH

    make_slide(prs, "title", title_heading,
               subheading=title_subheading, footnote=title_footnote)

    total = len(sections)
    for i, heading in enumerate(sections, start=1):
        make_slide(prs, "divider", heading, index=i, total=total)

    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    prs.save(out_path)
    print(f"deck -> {out_path}  ({len(prs.slides._sldIdLst)} slides)")
    return out_path


if __name__ == "__main__":
    build()
